"""empty message

Revision ID: 9c2a5cedd9ee
Revises: de6a75ac7eea
Create Date: 2022-02-09 18:20:43.228856

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c2a5cedd9ee'
down_revision = 'de6a75ac7eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=250), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.String(length=10000), nullable=False),
    sa.Column('slug', sa.String(length=2000), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('tag', sa.String(length=1000), nullable=False),
    sa.Column('keywords', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('author', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=10000), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=2000), nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('hidden', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('image', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('tag', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('keywords', mysql.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('blog')
    # ### end Alembic commands ###
